<?php

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Info(version: '1.0.0', title: 'Hummingbed Property API', description: 'Property marketplace API for listings, brokers, saved properties, enquiries, and viewing appointments.')]
#[OA\Server(url: '/', description: 'Current application')]
#[OA\SecurityScheme(securityScheme: 'sanctum', type: 'http', scheme: 'bearer', bearerFormat: 'Token')]
#[OA\Schema(
    schema: 'ApiResponse',
    properties: [
        new OA\Property(property: 'status', type: 'string', example: 'success'),
        new OA\Property(property: 'message', type: 'string', nullable: true),
        new OA\Property(property: 'data', type: 'object', nullable: true),
    ],
    type: 'object'
)]
#[OA\Post(path: '/api/v1/auth/register', summary: 'Register an account', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['name', 'email', 'password', 'password_confirmation'], properties: [new OA\Property(property: 'name', type: 'string'), new OA\Property(property: 'email', type: 'string', format: 'email'), new OA\Property(property: 'password', type: 'string', format: 'password'), new OA\Property(property: 'password_confirmation', type: 'string', format: 'password'), new OA\Property(property: 'role', type: 'string', enum: ['customer', 'broker'])])), tags: ['Authentication'], responses: [new OA\Response(response: 201, description: 'Account created')])]
#[OA\Post(path: '/api/v1/auth/login', summary: 'Log in and receive a bearer token', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['email', 'password'], properties: [new OA\Property(property: 'email', type: 'string', format: 'email', example: 'ada@example.com'), new OA\Property(property: 'password', type: 'string', format: 'password', example: 'password123')])), tags: ['Authentication'], responses: [new OA\Response(response: 200, description: 'Authenticated', content: new OA\JsonContent(ref: '#/components/schemas/AuthResponse')), new OA\Response(response: 422, ref: '#/components/responses/ValidationError')])]
#[OA\Get(path: '/api/v1/auth/me', summary: 'Get the authenticated account', security: [['sanctum' => []]], tags: ['Authentication'], responses: [new OA\Response(response: 200, description: 'Current account')])]
#[OA\Post(path: '/api/v1/auth/logout', summary: 'Revoke the current token', security: [['sanctum' => []]], tags: ['Authentication'], responses: [new OA\Response(response: 200, description: 'Logged out')])]
#[OA\Get(path: '/api/v1/properties', summary: 'Search and paginate properties', tags: ['Properties'], parameters: [new OA\Parameter(name: 'city', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'property_type', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'status', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'min_price', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'max_price', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'amenity', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'featured', in: 'query', schema: new OA\Schema(type: 'boolean')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', maximum: 100))], responses: [new OA\Response(response: 200, description: 'Paginated properties')])]
#[OA\Post(path: '/api/v1/properties', summary: 'Create a property', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/PropertyInput')), security: [['sanctum' => []]], tags: ['Properties'], responses: [new OA\Response(response: 201, description: 'Property created'), new OA\Response(response: 401, ref: '#/components/responses/Unauthorized'), new OA\Response(response: 403, ref: '#/components/responses/Forbidden'), new OA\Response(response: 422, ref: '#/components/responses/ValidationError')])]
#[OA\Get(path: '/api/v1/properties/{id}', summary: 'Get a property', tags: ['Properties'], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Property details'), new OA\Response(response: 404, description: 'Not found')])]
#[OA\Put(path: '/api/v1/properties/{id}', summary: 'Replace a property', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/PropertyInput')), security: [['sanctum' => []]], tags: ['Properties'], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Property updated'), new OA\Response(response: 401, ref: '#/components/responses/Unauthorized'), new OA\Response(response: 403, ref: '#/components/responses/Forbidden'), new OA\Response(response: 422, ref: '#/components/responses/ValidationError')])]
#[OA\Patch(path: '/api/v1/properties/{id}', summary: 'Partially update a property', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/PropertyInput')), security: [['sanctum' => []]], tags: ['Properties'], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Property updated'), new OA\Response(response: 401, ref: '#/components/responses/Unauthorized'), new OA\Response(response: 403, ref: '#/components/responses/Forbidden'), new OA\Response(response: 422, ref: '#/components/responses/ValidationError')])]
#[OA\Delete(path: '/api/v1/properties/{id}', summary: 'Delete a property', security: [['sanctum' => []]], tags: ['Properties'], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Property deleted')])]
#[OA\Get(path: '/api/v1/brokers', summary: 'List brokers', tags: ['Brokers'], responses: [new OA\Response(response: 200, description: 'Broker list')])]
#[OA\Post(path: '/api/v1/brokers', summary: 'Create a broker profile', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/BrokerInput')), security: [['sanctum' => []]], tags: ['Brokers'], responses: [new OA\Response(response: 201, description: 'Broker created'), new OA\Response(response: 401, ref: '#/components/responses/Unauthorized'), new OA\Response(response: 403, ref: '#/components/responses/Forbidden'), new OA\Response(response: 422, ref: '#/components/responses/ValidationError')])]
#[OA\Get(path: '/api/v1/brokers/{id}', summary: 'Get a broker', tags: ['Brokers'], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Broker details')])]
#[OA\Put(path: '/api/v1/brokers/{id}', summary: 'Replace a broker profile', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/BrokerInput')), security: [['sanctum' => []]], tags: ['Brokers'], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Broker updated'), new OA\Response(response: 403, ref: '#/components/responses/Forbidden'), new OA\Response(response: 422, ref: '#/components/responses/ValidationError')])]
#[OA\Patch(path: '/api/v1/brokers/{id}', summary: 'Partially update a broker', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/BrokerInput')), security: [['sanctum' => []]], tags: ['Brokers'], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Broker updated'), new OA\Response(response: 403, ref: '#/components/responses/Forbidden'), new OA\Response(response: 422, ref: '#/components/responses/ValidationError')])]
#[OA\Delete(path: '/api/v1/brokers/{id}', summary: 'Delete a broker', security: [['sanctum' => []]], tags: ['Brokers'], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Broker deleted')])]
#[OA\Get(path: '/api/v1/amenities', summary: 'List amenities', tags: ['Amenities'], responses: [new OA\Response(response: 200, description: 'Amenity list')])]
#[OA\Post(path: '/api/v1/amenities', summary: 'Create an amenity', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['name'], properties: [new OA\Property(property: 'name', type: 'string', maxLength: 100, example: 'Gym')])), security: [['sanctum' => []]], tags: ['Amenities'], responses: [new OA\Response(response: 201, description: 'Amenity created'), new OA\Response(response: 403, ref: '#/components/responses/Forbidden'), new OA\Response(response: 422, ref: '#/components/responses/ValidationError')])]
#[OA\Put(path: '/api/v1/properties/{property}/amenities', summary: 'Set property amenities', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['amenity_ids'], properties: [new OA\Property(property: 'amenity_ids', type: 'array', items: new OA\Items(type: 'integer'), example: [1, 3, 5])])), security: [['sanctum' => []]], tags: ['Amenities'], parameters: [new OA\Parameter(name: 'property', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Amenities synchronized'), new OA\Response(response: 403, ref: '#/components/responses/Forbidden'), new OA\Response(response: 422, ref: '#/components/responses/ValidationError')])]
#[OA\Post(path: '/api/v1/properties/{property}/images', summary: 'Add a hosted property image', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['url'], properties: [new OA\Property(property: 'url', type: 'string', format: 'uri'), new OA\Property(property: 'alt_text', type: 'string', nullable: true), new OA\Property(property: 'sort_order', type: 'integer', minimum: 0), new OA\Property(property: 'is_primary', type: 'boolean')])), security: [['sanctum' => []]], tags: ['Images'], parameters: [new OA\Parameter(name: 'property', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 201, description: 'Image added'), new OA\Response(response: 403, ref: '#/components/responses/Forbidden'), new OA\Response(response: 422, ref: '#/components/responses/ValidationError')])]
#[OA\Delete(path: '/api/v1/properties/{property}/images/{image}', summary: 'Delete a property image', security: [['sanctum' => []]], tags: ['Images'], parameters: [new OA\Parameter(name: 'property', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'image', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Image deleted')])]
#[OA\Get(path: '/api/v1/favorites', summary: 'List saved properties', security: [['sanctum' => []]], tags: ['Favorites'], responses: [new OA\Response(response: 200, description: 'Saved properties')])]
#[OA\Post(path: '/api/v1/properties/{property}/favorite', summary: 'Save a property', security: [['sanctum' => []]], tags: ['Favorites'], parameters: [new OA\Parameter(name: 'property', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 201, description: 'Property saved')])]
#[OA\Delete(path: '/api/v1/properties/{property}/favorite', summary: 'Remove a saved property', security: [['sanctum' => []]], tags: ['Favorites'], parameters: [new OA\Parameter(name: 'property', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Favorite removed')])]
#[OA\Post(path: '/api/v1/properties/{property}/inquiries', summary: 'Submit a property enquiry', description: 'Public endpoint. If a valid Sanctum token is supplied, the enquiry is associated with that account.', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['name', 'email', 'message'], properties: [new OA\Property(property: 'name', type: 'string', maxLength: 255, example: 'Ada Okafor'), new OA\Property(property: 'email', type: 'string', format: 'email'), new OA\Property(property: 'phone_number', type: 'string', nullable: true, maxLength: 30), new OA\Property(property: 'message', type: 'string', maxLength: 5000, example: 'Is this property still available?')])), tags: ['Inquiries'], parameters: [new OA\Parameter(name: 'property', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 201, description: 'Enquiry submitted', content: new OA\JsonContent(ref: '#/components/schemas/Inquiry')), new OA\Response(response: 404, ref: '#/components/responses/NotFound'), new OA\Response(response: 422, ref: '#/components/responses/ValidationError')])]
#[OA\Get(path: '/api/v1/inquiries', summary: 'List enquiries received by a broker', security: [['sanctum' => []]], tags: ['Inquiries'], responses: [new OA\Response(response: 200, description: 'Enquiry list')])]
#[OA\Patch(path: '/api/v1/inquiries/{inquiry}', summary: 'Update enquiry status', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['status'], properties: [new OA\Property(property: 'status', type: 'string', enum: ['new', 'contacted', 'closed'])])), security: [['sanctum' => []]], tags: ['Inquiries'], parameters: [new OA\Parameter(name: 'inquiry', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Enquiry updated'), new OA\Response(response: 403, ref: '#/components/responses/Forbidden'), new OA\Response(response: 422, ref: '#/components/responses/ValidationError')])]
#[OA\Get(path: '/api/v1/appointments', summary: 'List customer viewing appointments', security: [['sanctum' => []]], tags: ['Appointments'], responses: [new OA\Response(response: 200, description: 'Appointment list')])]
#[OA\Post(path: '/api/v1/properties/{property}/appointments', summary: 'Request a viewing appointment', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['scheduled_at'], properties: [new OA\Property(property: 'scheduled_at', type: 'string', format: 'date-time', example: '2026-08-20T14:00:00+01:00'), new OA\Property(property: 'notes', type: 'string', nullable: true, maxLength: 2000)])), security: [['sanctum' => []]], tags: ['Appointments'], parameters: [new OA\Parameter(name: 'property', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 201, description: 'Viewing requested', content: new OA\JsonContent(ref: '#/components/schemas/Appointment')), new OA\Response(response: 401, ref: '#/components/responses/Unauthorized'), new OA\Response(response: 422, ref: '#/components/responses/ValidationError')])]
#[OA\Patch(path: '/api/v1/appointments/{appointment}/cancel', summary: 'Cancel a viewing appointment', security: [['sanctum' => []]], tags: ['Appointments'], parameters: [new OA\Parameter(name: 'appointment', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Viewing cancelled')])]
#[OA\Get(path: '/api/v1/broker/appointments', summary: 'List viewing requests received by a broker', security: [['sanctum' => []]], tags: ['Appointments'], responses: [new OA\Response(response: 200, description: 'Broker appointment list')])]
#[OA\Patch(path: '/api/v1/broker/appointments/{appointment}', summary: 'Update a viewing request', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['status'], properties: [new OA\Property(property: 'status', type: 'string', enum: ['confirmed', 'completed', 'cancelled'])])), security: [['sanctum' => []]], tags: ['Appointments'], parameters: [new OA\Parameter(name: 'appointment', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Viewing updated'), new OA\Response(response: 403, ref: '#/components/responses/Forbidden'), new OA\Response(response: 422, ref: '#/components/responses/ValidationError')])]
final class ApiDocumentation
{
}
