<?php

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Schema(schema: 'ErrorResponse', required: ['status', 'message'], properties: [new OA\Property(property: 'status', type: 'string', example: 'failed'), new OA\Property(property: 'message', type: 'string', example: 'The given data was invalid.'), new OA\Property(property: 'errors', type: 'object', nullable: true)], type: 'object')]
#[OA\Schema(schema: 'User', required: ['id', 'name', 'email', 'role'], properties: [new OA\Property(property: 'id', type: 'integer', example: 1), new OA\Property(property: 'name', type: 'string', example: 'Ada Okafor'), new OA\Property(property: 'email', type: 'string', format: 'email', example: 'ada@example.com'), new OA\Property(property: 'role', type: 'string', enum: ['customer', 'broker', 'admin'], example: 'customer')], type: 'object')]
#[OA\Schema(schema: 'AuthResponse', required: ['status', 'data'], properties: [new OA\Property(property: 'status', type: 'string', example: 'success'), new OA\Property(property: 'data', required: ['user', 'token'], properties: [new OA\Property(property: 'user', ref: '#/components/schemas/User'), new OA\Property(property: 'token', type: 'string', example: '1|sanctum-token')], type: 'object')], type: 'object')]
#[OA\Schema(schema: 'Broker', required: ['id', 'name', 'address', 'city', 'zip_code', 'phone_number'], properties: [new OA\Property(property: 'id', type: 'integer', example: 1), new OA\Property(property: 'user_id', type: 'integer', nullable: true, example: 2), new OA\Property(property: 'name', type: 'string', example: 'Hummingbed Realty'), new OA\Property(property: 'address', type: 'string', example: '15 Admiralty Way'), new OA\Property(property: 'city', type: 'string', example: 'Lagos'), new OA\Property(property: 'zip_code', type: 'string', example: '101233'), new OA\Property(property: 'phone_number', type: 'string', example: '+2348012345678'), new OA\Property(property: 'logo', type: 'string', format: 'uri', nullable: true)], type: 'object')]
#[OA\Schema(schema: 'PropertyCharacteristic', properties: [new OA\Property(property: 'price', type: 'integer', format: 'int64', example: 75000000), new OA\Property(property: 'bedrooms', type: 'integer', example: 4), new OA\Property(property: 'bathrooms', type: 'integer', nullable: true, example: 4), new OA\Property(property: 'square_feet', type: 'integer', example: 2500), new OA\Property(property: 'price_square_feet', type: 'integer', example: 30000), new OA\Property(property: 'property_type', type: 'string', enum: ['self-contained', 'one-bedroom-flat', 'two-bedroom-flat', 'three-bedroom-flat', 'bungalow', 'duplex']), new OA\Property(property: 'status', type: 'string', enum: ['sold', 'on sale', 'on hold'])], type: 'object')]
#[OA\Schema(schema: 'PropertyImage', properties: [new OA\Property(property: 'id', type: 'integer', example: 10), new OA\Property(property: 'url', type: 'string', format: 'uri', example: 'https://cdn.example.com/properties/10/front.jpg'), new OA\Property(property: 'alt_text', type: 'string', nullable: true, example: 'Front view'), new OA\Property(property: 'sort_order', type: 'integer', example: 0), new OA\Property(property: 'is_primary', type: 'boolean', example: true)], type: 'object')]
#[OA\Schema(schema: 'Amenity', properties: [new OA\Property(property: 'id', type: 'integer', example: 1), new OA\Property(property: 'name', type: 'string', example: '24-hour Power'), new OA\Property(property: 'slug', type: 'string', example: '24-hour-power')], type: 'object')]
#[OA\Schema(schema: 'Property', properties: [new OA\Property(property: 'id', type: 'integer', example: 5), new OA\Property(property: 'attributes', properties: [new OA\Property(property: 'address', type: 'string', example: '12 Admiralty Way'), new OA\Property(property: 'listing_type', type: 'string', enum: ['open listing', 'sell listing', 'exclusive agency listing', 'net listing']), new OA\Property(property: 'city', type: 'string', example: 'Lagos'), new OA\Property(property: 'zip_code', type: 'string', example: '101233'), new OA\Property(property: 'description', type: 'string'), new OA\Property(property: 'build_year', type: 'integer', example: 2020), new OA\Property(property: 'is_featured', type: 'boolean'), new OA\Property(property: 'published_at', type: 'string', format: 'date-time', nullable: true)], type: 'object'), new OA\Property(property: 'characteristics', ref: '#/components/schemas/PropertyCharacteristic'), new OA\Property(property: 'broker', ref: '#/components/schemas/Broker'), new OA\Property(property: 'images', type: 'array', items: new OA\Items(ref: '#/components/schemas/PropertyImage')), new OA\Property(property: 'amenities', type: 'array', items: new OA\Items(ref: '#/components/schemas/Amenity')), new OA\Property(property: 'is_favorite', type: 'boolean', nullable: true)], type: 'object')]
#[OA\Schema(schema: 'Inquiry', properties: [new OA\Property(property: 'id', type: 'integer'), new OA\Property(property: 'property_id', type: 'integer'), new OA\Property(property: 'name', type: 'string'), new OA\Property(property: 'email', type: 'string', format: 'email'), new OA\Property(property: 'phone_number', type: 'string', nullable: true), new OA\Property(property: 'message', type: 'string'), new OA\Property(property: 'status', type: 'string', enum: ['new', 'contacted', 'closed'])], type: 'object')]
#[OA\Schema(schema: 'Appointment', properties: [new OA\Property(property: 'id', type: 'integer'), new OA\Property(property: 'property_id', type: 'integer'), new OA\Property(property: 'user_id', type: 'integer'), new OA\Property(property: 'scheduled_at', type: 'string', format: 'date-time'), new OA\Property(property: 'status', type: 'string', enum: ['pending', 'confirmed', 'completed', 'cancelled']), new OA\Property(property: 'notes', type: 'string', nullable: true)], type: 'object')]
#[OA\Schema(schema: 'BrokerInput', required: ['name', 'address', 'phone_number', 'city', 'zip_code'], properties: [new OA\Property(property: 'name', type: 'string', maxLength: 255), new OA\Property(property: 'address', type: 'string', maxLength: 255), new OA\Property(property: 'phone_number', type: 'string', maxLength: 30), new OA\Property(property: 'city', type: 'string', maxLength: 100), new OA\Property(property: 'zip_code', type: 'string', maxLength: 20), new OA\Property(property: 'logo', type: 'string', format: 'uri', nullable: true)], type: 'object')]
#[OA\Schema(schema: 'PropertyInput', required: ['broker_id', 'address', 'listing_type', 'city', 'zip_code', 'description', 'build_year', 'price', 'bedrooms', 'square_feet', 'price_square_feet', 'property_type', 'status'], properties: [new OA\Property(property: 'broker_id', type: 'integer'), new OA\Property(property: 'address', type: 'string', maxLength: 255), new OA\Property(property: 'listing_type', type: 'string', enum: ['open listing', 'sell listing', 'exclusive agency listing', 'net listing']), new OA\Property(property: 'city', type: 'string', maxLength: 100), new OA\Property(property: 'zip_code', type: 'string', maxLength: 20), new OA\Property(property: 'description', type: 'string'), new OA\Property(property: 'build_year', type: 'integer', minimum: 1800, example: 2020), new OA\Property(property: 'price', type: 'integer', minimum: 0), new OA\Property(property: 'bedrooms', type: 'integer', minimum: 0, maximum: 100), new OA\Property(property: 'bathrooms', type: 'integer', nullable: true, minimum: 0, maximum: 100), new OA\Property(property: 'square_feet', type: 'integer', minimum: 1), new OA\Property(property: 'price_square_feet', type: 'integer', minimum: 0), new OA\Property(property: 'property_type', type: 'string', enum: ['self-contained', 'one-bedroom-flat', 'two-bedroom-flat', 'three-bedroom-flat', 'bungalow', 'duplex']), new OA\Property(property: 'status', type: 'string', enum: ['sold', 'on sale', 'on hold'])], type: 'object')]
#[OA\Response(response: 'Unauthorized', description: 'Missing or invalid bearer token', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))]
#[OA\Response(response: 'Forbidden', description: 'The authenticated account does not own the resource', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))]
#[OA\Response(response: 'NotFound', description: 'Resource not found', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))]
#[OA\Response(response: 'ValidationError', description: 'Request validation failed', content: new OA\JsonContent(ref: '#/components/schemas/ErrorResponse'))]
final class ComponentSchemas
{
}
